name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
    contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }} and ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            go_arch: amd64
          - os: linux
            arch: arm64
            go_arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      - name: Build
        run: |
          go env
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.go_arch }} go build -o restartools-${{ matrix.arch }} ./

      - name: Display built file
        run: |
          ls -l

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            restartools-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}